Repository A7-TC2-TeamCode200/MRLA_Front, pull requests merged in 2022-12, with the labels that each got.

#12 Feat : 메인 페이지 및 커뮤니케이션 페이지 작성
  static/community.html
  static/static/css/community.css
  static/static/js/community.js
Labels: enhancement

#26 Feat : 커뮤니티 게시글 검색 기능 추가
  static/css/community_search.css
  static/js/api.js
  static/js/community_search.js
  templates/community.html
  templates/community_search.html
Labels: enhancement

#30 Feat : 인트로, 메인 기능 추가
  static/css/intro_2.css
  static/css/main.css
  static/css/map_category.css
  static/js/api.js
  static/js/community.js
  static/js/main.js
  static/js/map_category.js
  templates/community.html
  templates/intro_2.html
  templates/main.html
  templates/map_category.html
  templates/profile_update.html
  templates/restaurants_nearby.html
Labels: enhancement

#37 Style : 근처 맛집, 고객센터 CSS 수정
  static/css/restaurants_nearby.css
  static/css/service.css
  static/css/with_who.css
  static/js/main.js
  templates/restaurants_nearby.html
Labels: enhancement

#38 Fix : 고객센터 게시글 디테일 접근 권한 기능 수정
  static/js/api.js
  templates/service.html
Labels: bug

#39 Feat : 커뮤니티 게시글 등록 기능 추가
  static/css/community.css
  static/js/api.js
  static/js/community.js
  templates/community.html
Labels: enhancement

#43 Refact : 페이지 이동 로직 변경
  README.md
  static/css/main.css
  static/js/signin_signup.js
  templates/main.html
  templates/signin_signup.html
Labels: enhancement

#44 Feat : 커뮤니티 상세 페이지, 프로필 페이지 하단 탭 기능 추가
  static/css/community.css
  static/css/community_detail.css
  static/css/profile.css
  static/css/profile_community.css
  static/css/with_who.css
  static/js/api.js
  static/js/community.js
  static/js/community_detail.js
  static/js/profile.js
  static/js/profile_community.js
  static/js/profile_update.js
  static/js/with_who.js
  templates/community.html
  templates/community_detail.html
Labels: enhancement

#49 Fix : 커뮤니티 게시글 검색 기능 수정
  static/css/community_search.css
  static/js/community_search.js
  templates/community_search.html
Labels: bug

#60 Fix : 메뉴 디테일/근처 맛집 찾기 페이지 프로필 드롭다운 수정
  static/js/api.js
  static/js/map_search.js
  templates/community.html
  templates/community_detail.html
  templates/community_search.html
  templates/food_detail.html
  templates/main.html
  templates/map_search.html
  templates/profile.html
  templates/profile_community.html
  templates/profile_update.html
  templates/restaurants_nearby.html
  templates/service.html
  templates/service_detail.html
  templates/with_who.html
Labels: bug, enhancement

#61 Feat : 근처 맛집 페이지 카테고리 기능 추가
  static/css/community.css
  static/css/restaurants_nearby.css
  static/css/service_detail.css
  static/css/with_who.css
  static/js/map_search.js
  static/js/restaurants_nearby.js
  templates/restaurants_nearby.html
Labels: enhancement

#69 서버 배포를 위한 최종 PR(1차 수정본)
  static/css/map_search.css
  static/css/restaurants_nearby.css
  static/js/map_search.js
  static/js/restaurants_nearby.js
  templates/map_search.html
  templates/restaurants_nearby.html
Labels: bug, enhancement

#72 Feat : 근처 맛집 페이지 '카페' 카테고리 추가
  static/css/intro.css
  static/css/restaurants_nearby.css
  static/js/service_detail.js
  templates/intro.html
  templates/restaurants_nearby.html
Labels: enhancement

#73 Fix : 프로필 페이지 버그 수정
  static/css/community.css
  static/css/community_detail.css
  static/css/profile.css
  static/css/profile_community.css
  static/js/api.js
  static/js/profile.js
  static/js/profile_community.js
  templates/community.html
  templates/profile.html
  templates/profile_community.html
Labels: bug

#74 Style : 모든 페이지 헤더에 마스코트 아이콘 추가
  static/css/community.css
  static/css/community_detail.css
  static/css/community_search.css
  static/css/food_detail.css
  static/css/main.css
  static/css/map_search.css
  static/css/profile.css
  static/css/profile_community.css
  static/css/profile_update.css
  static/css/restaurants_nearby.css
  static/css/service.css
  static/css/service_detail.css
  static/css/with_who.css
  templates/community.html
  templates/community_detail.html
  templates/community_search.html
  templates/food_detail.html
  templates/main.html
  templates/map_search.html
  templates/profile.html
  templates/profile_community.html
  templates/profile_update.html
  templates/restaurants_nearby.html
  templates/service.html
  templates/service_detail.html
  templates/with_who.html
Labels: enhancement

#75 Style : 인트로 색감 수정
  static/css/intro.css
Labels: enhancement

#78 Feat : 서비스 종료 시 토큰 삭제 기능 추가
  static/js/api.js
Labels: enhancement

#81 Fix : 커뮤니티 게시글 검색 기능 수정
  static/css/community.css
  static/js/api.js
  static/js/community_search.js
  static/js/signin_signup.js
  templates/community.html
Labels: bug, enhancement

#85 Feat : 회원 탈퇴 기능 추가
  static/css/community_detail.css
  static/css/profile_update.css
  static/js/api.js
  static/js/profile_update.js
  templates/profile_update.html
Labels: enhancement

#86 Feat : 팔로잉/팔로워 목록 기능 추가
  static/css/community_detail.css
  static/css/profile.css
  static/css/profile_community.css
  static/css/profile_my_community.css
  static/js/api.js
  static/js/profile.js
  static/js/profile_community.js
  static/js/profile_my_community.js
Labels: enhancement

#89 Style : 이미지 크기 조절, 불필요 코드 삭제
  static/css/community_detail.css
  static/css/main.css
  static/js/api.js
Labels: enhancement
